export interface RoutingTarget { profileId: string; kind: "node" | "group"; name: string }
export interface ProcessRule { id: string; enabled: boolean; label: string; matchKind: "path" | "name"; matchValue: string; action: "proxy" | "direct" | "reject"; target: RoutingTarget | null; includeDescendants: boolean; ruleMode?: "inherit" | "strict" }
export interface DnsRule { id: string; enabled: boolean; domainKind: "exact" | "suffix"; domain: string; resolverUrl: string; target: RoutingTarget }
export interface BundleRoute { id: string; name: string; mainExe: string; enabled: boolean; mainTarget: RoutingTarget | null; dnsTarget: RoutingTarget | null; port: number; mode: string; domains?: string[]; fallback?: "rules" | "system" | "direct" }
export interface RoutingOverrides { schemaVersion: number; revision: number; processEnabled: boolean; dnsEnabled: boolean; processRules: ProcessRule[]; dnsRules: DnsRule[]; bundles?: BundleRoute[]; nextBundlePort?: number; retainForeignTargets?: boolean }
export interface ProcessEntry { identity: string; pid: number; parentPid: number; name: string; executablePath: string | null; parentIdentity: string | null }
export interface RoutingView { trafficDriver?: "app_proxy" | "tun"; capture: { active: boolean; transitioning?: boolean; message: string; tcpConnections: number; udpPackets: number; dnsQueries: number; failures: number; unclassified: number; lastError?: string | null; recentErrors?: { timeMs: number; destination: string; stage: string; kind: string; systemCode: number | null }[] }; config: RoutingOverrides; targets: RoutingTarget[]; preservedTargets?: RoutingTarget[]; running: boolean; appliedRevision: number | null; appliedGeneration: number | null; unavailableRules: string[]; tracking: { generation: number; subscribed: boolean; error: string | null; warnings?: string[]; entries: ProcessEntry[]; derived: ProcessRule[]; conflicts: string[] } }
export interface ProcessSelection { identity: string; executablePath: string }
export interface DnsDiagnostic { durationMs: number; answers: string[]; message: string }
