//! Node option names verified against the bundled Mihomo v1.19.31 option structs.
//! Filesystem paths and dependency/interface overrides are deliberately excluded.
pub fn fields(kind: &str) -> &'static [&'static str] {
    match kind {
        "ss" => &["password", "cipher", "udp", "plugin", "plugin-opts", "udp-over-tcp", "udp-over-tcp-version", "client-fingerprint"],
        "ssr" => &["password", "cipher", "obfs", "obfs-param", "protocol", "protocol-param", "udp"],
        "vmess" => &["uuid", "alterId", "cipher", "udp", "network", "tls", "alpn", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "servername", "ech-opts", "shadow-tls-opts", "restls-opts", "jls-opts", "reality-opts", "tlsmirror-opts", "mekya-opts", "mkcp-opts", "http-opts", "h2-opts", "grpc-opts", "ws-opts", "packet-addr", "xudp", "packet-encoding", "global-padding", "authenticated-length", "client-fingerprint"],
        "vless" => &["uuid", "flow", "tls", "alpn", "udp", "packet-addr", "xudp", "packet-encoding", "encryption", "network", "ech-opts", "shadow-tls-opts", "restls-opts", "jls-opts", "reality-opts", "http-opts", "h2-opts", "grpc-opts", "ws-opts", "xhttp-opts", "ws-headers", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "servername", "client-fingerprint"],
        "trojan" => &["password", "alpn", "sni", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "udp", "network", "ech-opts", "shadow-tls-opts", "restls-opts", "jls-opts", "reality-opts", "grpc-opts", "ws-opts", "ss-opts", "client-fingerprint"],
        "hysteria" => &["ports", "protocol", "obfs-protocol", "up", "up-speed", "down", "down-speed", "auth", "auth-str", "obfs", "sni", "ech-opts", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "alpn", "recv-window-conn", "recv-window", "disable-mtu-discovery", "fast-open", "hop-interval"],
        "hysteria2" => &["ports", "hop-interval", "up", "down", "password", "obfs", "obfs-password", "obfs-min-packet-size", "obfs-max-packet-size", "sni", "ech-opts", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "alpn", "cwnd", "bbr-profile", "udp-mtu", "handshake-timeout", "realm-opts", "initial-stream-receive-window", "max-stream-receive-window", "initial-connection-receive-window", "max-connection-receive-window"],
        "wireguard" => &["ip", "ipv6", "private-key", "workers", "mtu", "udp", "persistent-keepalive", "ip-stack", "amnezia-wg-option", "peers", "remote-dns-resolve", "dns", "refresh-server-ip-interval", "public-key", "pre-shared-key", "reserved", "allowed-ips"],
        "socks5" => &["username", "password", "tls", "udp", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key"],
        "http" => &["username", "password", "tls", "sni", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "headers"],
        "tuic" => &["token", "uuid", "password", "ip", "heartbeat-interval", "alpn", "reduce-rtt", "request-timeout", "udp-relay-mode", "congestion-controller", "disable-sni", "max-udp-relay-packet-size", "fast-open", "max-open-streams", "cwnd", "bbr-profile", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "recv-window-conn", "recv-window", "disable-mtu-discovery", "max-datagram-frame-size", "sni", "ech-opts", "udp-over-stream", "udp-over-stream-version"],
        "anytls" => &["password", "alpn", "sni", "ech-opts", "shadow-tls-opts", "restls-opts", "jls-opts", "client-fingerprint", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "udp", "client-metadata", "idle-session-check-interval", "idle-session-timeout", "min-idle-session", "disable-reuse"],
        "snell" => &["psk", "udp", "version", "reuse", "obfs-opts", "client-fingerprint"],
        "ssh" => &["username", "password", "private-key", "private-key-passphrase", "host-key", "host-key-algorithms"],
        "mieru" => &["port-range", "transport", "udp", "username", "password", "multiplexing", "handshake-mode", "traffic-pattern"],
        "shadowquic" => &["username", "password", "sni", "alpn", "quic-versions", "udp-over-stream", "zero-rtt", "keep-alive-interval", "congestion-controller", "up", "down", "cwnd", "bbr-profile", "recv-window-conn", "recv-window", "disable-mtu-discovery", "max-datagram-frame-size", "max-open-streams"],
        "gost-relay" => &["forward", "udp", "tls", "mux", "sni", "username", "password", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "client-fingerprint"],
        "sudoku" => &["key", "aead-method", "padding-min", "padding-max", "table-type", "enable-pure-downlink", "http-mask", "http-mask-mode", "http-mask-tls", "http-mask-host", "path-root", "multiplex", "http-mask-multiplex", "httpmask", "custom-table", "custom-tables"],
        "masque" => &["private-key", "public-key", "ip", "ipv6", "uri", "sni", "mtu", "udp", "handshake-timeout", "skip-cert-verify", "name-cert-verify", "network", "congestion-controller", "cwnd", "bbr-profile", "ip-stack", "remote-dns-resolve", "dns"],
        "trusttunnel" => &["username", "password", "alpn", "sni", "ech-opts", "client-fingerprint", "skip-cert-verify", "name-cert-verify", "fingerprint", "certificate", "private-key", "udp", "health-check", "quic", "congestion-controller", "cwnd", "bbr-profile", "max-connections", "min-streams", "max-streams"],
        "openvpn" => &["proto", "dev", "cipher", "data-ciphers", "data-ciphers-fallback", "auth", "comp-lzo", "ca", "cert", "key", "tls-auth", "key-direction", "tls-crypt", "tls-crypt-v2", "username", "password", "peer-info", "ping", "ping-restart", "tran-window", "handshake-timeout", "mtu", "udp", "ip-stack", "remote-dns-resolve", "dns"],
        "tailscale" => &["hostname", "auth-key", "control-url", "ephemeral", "udp", "accept-routes", "exit-node", "exit-node-allow-lan-access"],
        "zerotier" => &["network", "identity-secret", "mtu", "ip-stack", "physical-mtu", "udp", "remote-dns-resolve", "dns", "low-bandwidth", "encrypted-hello", "primary-port", "secondary-port", "tcp-fallback-mode", "tcp-fallback-relay", "orbit", "remote-trace-target", "remote-trace-level"],
        "easytier" => &["network-name", "network-secret", "hostname", "ipv4", "dhcp", "peers", "listeners", "no-listener", "mapped-listeners", "exit-nodes", "proxy-networks", "instance-name", "udp", "accept-dns", "enable-exit-node", "enable-encryption", "encryption-algorithm", "private-mode", "latency-first", "disable-p2p", "enable-kcp-proxy", "disable-kcp-input", "enable-quic-proxy", "disable-quic-input", "mtu", "tld-dns-zone", "secure-mode", "local-private-key", "local-public-key"],
        _ => &[],
    }
}
